### ISSUE TITLE
Allow for multiple Turtle objects

### ISSUE THREAD

**Issue by RelevantJesse** [nakov/TurtleGraphics.NET#2]
Is there a reason that the class is made static? I feel like it would be better for learning if it was made non-static. Also, having the ability to have multiple Turtle instances would be pretty valuable.

**Comment by nakov** [comment]
It can be modified to be **non-static**.

The reason to use `static` is that this simplifies the beginners, who don't know what is "class", "object", etc.
The target group for this library are 5-8 years old kids, who touch programming for their first time.
